### ISSUE TITLE
when run python cv.py 

### ISSUE THREAD

**Issue by MrRace** [jilljenn/qna#1]
when running `python cv.py` the error comes below: FileNotFoundError: [Errno 2] Can not find 'timss/subset.json'.
Therefore how to get the subset.json.
When runnig `sh start.sh` the same error.It need some files:
```
data/timss2003.json
data/qmatrix-timss2003.json
```
How to get them?
Thanks a lot!

**Comment by jilljenn** [comment]
I will look at this today! Thanks for reporting!

**Comment by jilljenn** [comment]
It is now fixed. The problem is, `DEBUG` should have been set to `True` in the `conf.py` file.

I also updated the README: https://github.com/jilljenn/qna

Feel free to ask any questions. And you should check my [Knowledge Tracing Machines tutorial](https://github.com/jilljenn/ktm) as well which is fully Python, so requires less maintaining.
